### ISSUE TITLE
Request for a new instruction video just like your previous one.

### ISSUE THREAD

**Issue by taishi55** [ivanhofer/typesafe-i18n-demo-sveltekit#15]
Hi, I'm wondering if this installation approach is also changed due to a major change of Sveltekit.  
Some comments say the instruction of the video is outdated. https://www.youtube.com/watch?v=C6O5pMMMTG0

It would be great if you can post a beginner friendly instruction video for the new Sveltekit!
I believe this library is the most effective for SSR internationalization, and I'd like to learn more about this library for Svelekit.

**Comment by ivanhofer** [comment]
Hi, the installation process is still the same.
The video was created with an early version of SvelteKit. A lot has changed since then. But the concepts are almost identical. Most changes are related to moving some code parts to another file.
Also a few improvements and minor bug fixes were made since then.

I try to keep this repository up2date with the latest SvelteKit changes. You can watch the video to learn why we need to do certain things and then come back to the code to see how it's used inside the latest SvelteKit version.


I don't see the need for a new video since it involves some effort to create a new one.
